{% set name = "pyworkdir" %}
{% set version = "0.3.1" %}
{% set sha256 = "1ae1c36485bab37c82fb2f32bba285ba8db1e07cac04a9e2fb64f8cef284755a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/olllom/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - workdir = pyworkdir.main:entrypoint

requirements:
  host:
    - python >=3.6
    - pip
    - jinja2
    - pyyaml
    - click >=6.0
  run:
    - python >=3.6
    - jinja2
    - pyyaml
    - click >=6.0

test:
  imports:
    - pyworkdir
  commands:
    - workdir --help

about:
  home: http://github.com/olllom/pyworkdir
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python working directories'
  description: Python working directories
  doc_url: http://pyworkdir.readthedocs.io/
  dev_url: https://github.com/olllom/pyworkdir

extra:
  recipe-maintainers:
    - olllom
