travis:
  secure:
    BINSTAR_TOKEN: EHYhOD9btd/TeN4I15nIEOXQ2expwP+J9e2Wdcl5DtkQ/KMPyxAtg81JaIufbvIfzl/VY0jyq/ORJzUtoozbIz46UYfUzAE29VNr2IpLU75scNgCCEzvLs9i28+tw3b1m+/+mBmVPosEn85LOIbAerYUPV0q9nGsBNkg8huOc4EMXBJ6Iw4QPL3TcFcahYMMtuAimla1EfxH3v1bR7Ep98jQU92RR4O02wXCILYpqBHxq3W+HXSzxJIVCyuq6pWG4eWDA5DCnxJ2pOIJd7Nt+dKqNIWX+KTgrRlVw+gMUIvDhwrIhfPFKQWWnwQRmHOdCbUSCUu6ElZd6E36jMpoBdnjQz2PdELuZ2RHJhq23yumT2xEbSvollxI77yR6jBwkIsjB0jBuLlhSQIO6ZpALks6uPCftFSptkK9/fUeM0rcfO443z40A6rkLfdNMzL3QgG3wLZyqJZtEm4F78Ut8jDbkJ7eqORb4aQKPiGGMucsBz+gefwbxB1EfPBOgEzrp+mc3Vzivdzmsxk8KnVTWzi68szwmXzQ7w+VidsyGRkoW2xMXj/K6KFAz/M5PHV+hvoAkNUVTqICmAoMEZPJ/VhW7lWxQbsTC1HBvWDlGYknfyTUzXewbqjb+J+bH0kmlGFprsJZ5a3g227L/Tr3oehny3ebpaNH/kKnm8VnstQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
